config/routes.rb
Rails.application.routes.draw do
  get 'angular/index'

  devise_for :users, :path => :session
  resources :todos, :except => [:new,:create]
  resources :users do
    resources :todos, shallow: true, :only => [:new,:create]
  end

  root 'angular#index'
  get '*path' => 'angular#index'

end

app/models/todo.rb
class Todo
  include Mongoid::Document
  include Mongoid::Timestamps
  belongs_to :user

  field :title, type: String
  field :description, type: String
  field :completion, type: Integer

  validates :user, presence: true
  validates :title, presence: true
  validates :completion, presence: true
  validates :completion, numericality: {greater_than: 0,less_than_or_equal_to: 100}

  after_initialize :add_created_at

  def add_created_at
    unless self.created_at.present?
      self.created_at = self.id.generation_time
      self.save
    end
  end
end

app/models/user.rb
class User
  include Mongoid::Document

  has_many :todos
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time

end

app/controllers/angular_controller.rb
class AngularController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html,:json

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:index,]
  respond_to :html, :json

  def index
    if @user
      @todos = @user.todos
    else
      @todos = Todo.all
    end
    respond_with(@todos)
  end

  def show
    respond_with(@todo)
  end

  def new
    @todo = Todo.new
    respond_with(@todo)
  end

  def edit
  end

  def create
    @todo = Todo.new(todo_params)
    @todo.save
    respond_with(@todo)
  end

  def update
    @todo.update(todo_params)
    respond_with(@todo)
  end

  def destroy
    @todo.destroy
    respond_with(@todo)
  end

  private
    def set_todo
      @todo = Todo.find(params[:id])
    end

    def set_user
      @user = User.find(params[:user_id]) rescue nil
    end

    def todo_params
      params.require(:todo).permit(:title, :description, :completion, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  respond_to :json

  def index
    @users = User.all
  end

  def show
    respond_with(@user)
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    @user.save
    respond_with(@user)
  end

  def update
    @user.update(user_params)
    respond_with(@user)
  end

  def destroy
    @user.destroy
    respond_with(@user)
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:email,:password)
    end
end

app/helpers/angular_helper.rb
module AngularHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/angular/index.html.erb
<div class="view-container">
    <div ui-view class="view-frame animate-view"></div>
</div>

app/views/layouts/_messages.html.haml
.alert-box(data-alert active-class="in" flash-alert="success" ng-show="flash.message")
  %span.alert-message {{flash.message}}
  %button.close(href="#") &times;

.alert-box.alert(data-alert active-class="in" flash-alert="error" ng-show="flash.message")
  %span.alert-message {{flash.message}}
  %button.close(href="#") &times;

.alert-box.info(data-alert active-class="in" flash-alert="info" ng-show="flash.message")
  %span.alert-message {{flash.message}}
  %button.close(href="#") &times;

app/views/layouts/_navigation.html.haml
-# navigation styled for Zurb Foundation 5
-# the syntax for data-topbar may need to change for Zurb Foundation 5
%nav.top-bar{"data-topbar" => true}
  %ul.title-area
    %li.name
      %a(ui-sref="index")Home
    %li.toggle-topbar.menu-icon
      %a{:href => "#"}
        Menu
  .top-bar-section
    %ul.right(ng-controller="UserCtrl")
      %li(ng-show="isAuthenticated")
        %a {{currentUser.email}}
      %li{"ng-show" => "!isAuthenticated"}
        %a.button{"ui-sref" => "sign_in"} Sign in
      %li{"ng-show" => "isAuthenticated"}
        %a.button{"ui-sref" => "sign_out"} Sign out

app/views/layouts/_navigation_links.html.haml
%li{"ng-show" => "!Auth.isAuthenticated()"}
    %a.button{"ui-sref" => "sign_in"} Sign in
%li{"ng-show" => "Auth.isAuthenticated()"}
    %a.button{"ui-sref" => "sign_out"} Sign out

app/views/layouts/application.html.haml
!!!
%html{'ng-app':'todoer'}
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Angular Mongo Todo List'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Angular Mongo Todo List'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    -# Modernizr is required for Zurb Foundation
    = javascript_include_tag 'vendor/modernizr'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      .large-8.columns.large-centered
        = render 'layouts/messages'
        = yield

app/views/todos/_form.html.haml
= simple_form_for(@todo) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :description
    = f.input :completion

  .form-actions
    = f.button :submit

app/views/todos/edit.html.haml
%h1 Editing todo

= render 'form'

= link_to 'Show', @todo, class: 'button info'
\|
= link_to 'Back', todos_path, class: 'button'

app/views/todos/index.html.haml
%h1 Listing todos

%table#todos
  %thead
    %tr
      %th Title
      %th Description
      %th Completion
      %th

  %tbody
    - @todos.each do |todo|
      %tr
        %td= todo.title
        %td= todo.description
        %td.progress.success.small-2
          %span.meter{style:"width: #{todo.completion}%"}
        %td.action-buttons
          =link_to 'Show', todo, class: 'button tiny info'
          =link_to 'Edit', edit_todo_path(todo), class: 'button tiny'
          =link_to 'Destroy', todo, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'button tiny alert'

%br
-if current_user
  = link_to 'New Todo', new_user_todo_path(user_id: current_user.id), class: 'button'

app/views/todos/new.html.haml
%h1 New todo

= render 'form'

= link_to 'Back', todos_path, class: 'button secondary'

app/views/todos/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @todo.title
%p
  %b Description:
  = @todo.description
%p
  %b Completion:
  = @todo.completion

= link_to 'Edit', edit_todo_path(@todo), class: 'button info'
\|
= link_to 'Back', todos_path, class: 'button secondary'